/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coronavirus;

import Clases.ArchivoEscrituraAdministrador;
import Clases.ArchivoEscrituraFarmacias;
import Clases.LecturaDeDatos;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 *
 * @author apple
 */
public class PantallaModificarFarmacia extends javax.swing.JFrame {
     int index;
    BaseDeDatosGeneral administradorbasededatos;
    
    public PantallaModificarFarmacia(int idx,BaseDeDatosGeneral pA) {
        administradorbasededatos = pA;
        initComponents();
        index=idx;
        List<ArchivoEscrituraFarmacias> ListaFarmacias= new ArrayList<>();
        ListaFarmacias = new LecturaDeDatos().ObtenerFarmacias();
        
        txtNombre.setText(String.valueOf(ListaFarmacias.get(idx).getNombreFarmacia()));
        cmbMunicipio.setSelectedItem(String.valueOf(ListaFarmacias.get(idx).getMunicipio()));
        cmbPrecio.setSelectedItem(String.valueOf(ListaFarmacias.get(idx).getPrecio()));
       }  
    public PantallaModificarFarmacia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnModificarFarmacias = new javax.swing.JButton();
        cmbMunicipio = new javax.swing.JComboBox<>();
        cmbPrecio = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/negro.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(631, 631));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Farmacias");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 120, 160, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 220, 60, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Municipio:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 270, 66, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precios:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 320, 50, 16);

        txtNombre.setToolTipText("");
        getContentPane().add(txtNombre);
        txtNombre.setBounds(140, 220, 130, 26);

        btnModificarFarmacias.setText("Modificar");
        btnModificarFarmacias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarFarmaciasActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarFarmacias);
        btnModificarFarmacias.setBounds(270, 520, 103, 29);

        cmbMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar:", "Zapopan", "Guadalajara", "Tlaquepaque", "El salto", "Ixtlahuacan", "Tlajomulco de zuñiga", "Juanacatlan", "Tonala", "Zapotlanejo" }));
        getContentPane().add(cmbMunicipio);
        cmbMunicipio.setBounds(140, 260, 130, 30);

        cmbPrecio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar:", "Muy accesible", "Accesible", "Caros" }));
        cmbPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPrecio);
        cmbPrecio.setBounds(140, 310, 130, 30);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(230, 570, 190, 29);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/negro.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(560, 100, 45, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/umbrella corporation.gif"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 500, 180);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/negro.jpg"))); // NOI18N
        jLabel5.setMinimumSize(new java.awt.Dimension(632, 636));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 690, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarFarmaciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarFarmaciasActionPerformed

       List<ArchivoEscrituraFarmacias> listaFarmacias= new ArrayList<>();
        LecturaDeDatos LD = new LecturaDeDatos();
//        
        listaFarmacias =LD.ObtenerFarmacias();
//        
        ArchivoEscrituraFarmacias FarmaciasTemp = new ArchivoEscrituraFarmacias();
       FarmaciasTemp.setNombreFarmacia(txtNombre.getText());
       FarmaciasTemp.setMunicipio(cmbMunicipio.getSelectedItem().toString());
       FarmaciasTemp.setPrecio(cmbPrecio.getSelectedItem().toString());
//        
        FarmaciasTemp.GuardarFarmacia2();
        listaFarmacias.set(index, FarmaciasTemp);
        listaFarmacias.get(index).BorrarFarmacia();
        for (Iterator<ArchivoEscrituraFarmacias> iterator = listaFarmacias.iterator(); iterator.hasNext();) {
            ArchivoEscrituraFarmacias next = iterator.next();
            next.GuardarFarmacia2();
        }
            
       administradorbasededatos.TablaFarmacias();
        
        dispose();
    

    }//GEN-LAST:event_btnModificarFarmaciasActionPerformed

    private void cmbPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPrecioActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaModificarFarmacia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificarFarmacias;
    private javax.swing.JComboBox<String> cmbMunicipio;
    private javax.swing.JComboBox<String> cmbPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
