/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coronavirus;

import Clases.ArchivoEscrituraFarmacias;
import Clases.ArchivoEscrituraHospitales;
import Clases.LecturaDeDatos;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 *
 * @author apple
 */
public class PantallaModificarHospitales extends javax.swing.JFrame {

    int index;
    BaseDeDatosGeneral administradorbasededatos;
    
    public PantallaModificarHospitales(int idx,BaseDeDatosGeneral pA) {
        administradorbasededatos = pA;
        initComponents();
        index=idx;
        List<ArchivoEscrituraHospitales> ListaHospitales= new ArrayList<>();
        ListaHospitales = new LecturaDeDatos().ObtenerHospitales();
        
        txtNombreHospital.setText(String.valueOf(ListaHospitales.get(idx).getNombreHospital()));
        cmbSeguro.setSelectedItem(String.valueOf(ListaHospitales.get(idx).getSeguro()));
        
       }  
    public PantallaModificarHospitales() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreHospital = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        cmbSeguro = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(631, 631));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hospitales");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(212, 115, 180, 98);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del hospital:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(106, 261, 143, 17);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Aceptan seguro de gastos medicos:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(6, 342, 243, 17);
        getContentPane().add(txtNombreHospital);
        txtNombreHospital.setBounds(261, 258, 198, 26);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(110, 510, 200, 40);

        cmbSeguro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar:", "Si", "No" }));
        getContentPane().add(cmbSeguro);
        cmbSeguro.setBounds(260, 340, 200, 27);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(328, 510, 180, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/umbrella corporation.gif"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 500, 180);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/negro.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 630, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
     
      List<ArchivoEscrituraHospitales> listaHospitales= new ArrayList<>();
        LecturaDeDatos LD = new LecturaDeDatos();
//        
        listaHospitales =LD.ObtenerHospitales();
//        
        ArchivoEscrituraHospitales HospitaleTemp = new ArchivoEscrituraHospitales();
       HospitaleTemp.setNombreHospital(txtNombreHospital.getText());
       HospitaleTemp.setSeguro(cmbSeguro.getSelectedItem().toString());
       
//        
        HospitaleTemp.GuardarHospital2();
        listaHospitales.set(index, HospitaleTemp);
        listaHospitales.get(index).BorrarHospitales();
        for (Iterator<ArchivoEscrituraHospitales> iterator = listaHospitales.iterator(); iterator.hasNext();) {
            ArchivoEscrituraHospitales next = iterator.next();
            next.GuardarHospital2();
        }
            
       administradorbasededatos.TablaHospitales();
        
        dispose();
       
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarHospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarHospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarHospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarHospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaModificarHospitales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbSeguro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtNombreHospital;
    // End of variables declaration//GEN-END:variables
}
