/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coronavirus;

import Clases.ArchivoEscrituraPaciente;
import java.io.File;
import java.util.Formatter;
import javax.swing.JOptionPane;

/**
 *
 * @author oscarjavierpereztorres
 */
public class RegistroPacienteAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form altaPacienteAdministrador
     */
    public RegistroPacienteAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Genero = new javax.swing.ButtonGroup();
        Municipio = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAltaNombrePacienteAdmin = new javax.swing.JTextField();
        txtEdadPacienteAdmin = new javax.swing.JTextField();
        txtAltaNumeroPacienteAdmin = new javax.swing.JTextField();
        txtAltaCorreoePacienteAdmin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnGuardarAdmin = new javax.swing.JButton();
        btnSalir7 = new javax.swing.JButton();
        btnRegresarMenuPrinc = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        cmbMunicipio = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(631, 631));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 200, 70, 16);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Edad: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 280, 38, 16);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numero:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 360, 60, 16);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correo: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 390, 50, 16);
        getContentPane().add(txtAltaNombrePacienteAdmin);
        txtAltaNombrePacienteAdmin.setBounds(90, 200, 160, 26);
        getContentPane().add(txtEdadPacienteAdmin);
        txtEdadPacienteAdmin.setBounds(90, 280, 40, 26);
        getContentPane().add(txtAltaNumeroPacienteAdmin);
        txtAltaNumeroPacienteAdmin.setBounds(90, 360, 160, 26);
        getContentPane().add(txtAltaCorreoePacienteAdmin);
        txtAltaCorreoePacienteAdmin.setBounds(90, 390, 160, 26);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Registro de pacientes administrador");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(150, 160, 440, 30);

        btnGuardarAdmin.setText("Guardar");
        btnGuardarAdmin.setToolTipText("");
        btnGuardarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarAdmin);
        btnGuardarAdmin.setBounds(190, 520, 180, 29);

        btnSalir7.setText("Salir");
        btnSalir7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir7);
        btnSalir7.setBounds(190, 560, 180, 29);

        btnRegresarMenuPrinc.setText("Regresar al menu anterior");
        btnRegresarMenuPrinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuPrincActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresarMenuPrinc);
        btnRegresarMenuPrinc.setBounds(160, 480, 240, 29);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Genero:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 240, 60, 20);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Municipio:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 310, 100, 30);

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar:", "Hombre ", "Mujer" }));
        getContentPane().add(cmbSexo);
        cmbSexo.setBounds(100, 240, 120, 27);

        cmbMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar:", "Zapopan", "Guadalajara", "Tlaquepaque", "El salto", "Ixtlahuacan", "Tlajomulco de zuñiga", "Juanacatlan", "Tonala", "Zapotlanejo" }));
        getContentPane().add(cmbMunicipio);
        cmbMunicipio.setBounds(100, 320, 130, 27);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/umbrella corporation.gif"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 500, 180);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/negro.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 630, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMenuPrincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuPrincActionPerformed
    AdministradorPrincipal adm=new AdministradorPrincipal();
    adm.setVisible(true);
    this.dispose();
      
    }//GEN-LAST:event_btnRegresarMenuPrincActionPerformed

    private void btnSalir7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir7ActionPerformed
         System.exit(WIDTH);
    }//GEN-LAST:event_btnSalir7ActionPerformed
  

    
    
    
    private void btnGuardarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAdminActionPerformed
//       Crear();
 ArchivoEscrituraPaciente AeP= new ArchivoEscrituraPaciente();
       
       
     
        AeP.setNombre(txtAltaNombrePacienteAdmin.getText());
        AeP.setMuniciopio(cmbMunicipio.getSelectedItem().toString());
        AeP.setCorreo(txtAltaCorreoePacienteAdmin.getText());
        AeP.setSexo(cmbSexo.getSelectedItem().toString());
        AeP.setEdad(Integer.parseInt(txtEdadPacienteAdmin.getText()));
        AeP.setNumero(Long.parseLong(txtAltaNumeroPacienteAdmin.getText()));
        
        try{
            if(AeP.GuardarPacientes()){ // Se llama la funcion guardar de alumno
            
            JOptionPane.showMessageDialog(this,"El paciente fue registrado exitosamente");
            
            txtAltaNombrePacienteAdmin.setText("");
            txtEdadPacienteAdmin.setText("");
            txtAltaCorreoePacienteAdmin.setText("");
            txtAltaNumeroPacienteAdmin.setText("");
            
            
       
      
     
       
      
            
            
            
            
            }
        }catch (Exception e) {
             System.out.println("Error ");
        }
    }//GEN-LAST:event_btnGuardarAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPacienteAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPacienteAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPacienteAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPacienteAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPacienteAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Genero;
    private javax.swing.ButtonGroup Municipio;
    private javax.swing.JButton btnGuardarAdmin;
    private javax.swing.JButton btnRegresarMenuPrinc;
    private javax.swing.JButton btnSalir7;
    private javax.swing.JComboBox<String> cmbMunicipio;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField txtAltaCorreoePacienteAdmin;
    private javax.swing.JTextField txtAltaNombrePacienteAdmin;
    private javax.swing.JTextField txtAltaNumeroPacienteAdmin;
    private javax.swing.JTextField txtEdadPacienteAdmin;
    // End of variables declaration//GEN-END:variables
}
