/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coronavirus;

import Clases.ArchivoEscrituraAdministrador;
import Clases.ArchivoEscrituraPaciente;
import Clases.LecturaDeDatos;
import java.io.File;
import java.util.ArrayList;
import java.util.Formatter;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author oscarjavierpereztorres
 */
public class RegistroAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form altaAdministrador
     */
    public RegistroAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuarioAdm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnGuardarAdmin = new javax.swing.JButton();
        btnSalir2 = new javax.swing.JButton();
        btnRegresarMenuPrinc = new javax.swing.JButton();
        txtpasword = new javax.swing.JPasswordField();
        btnCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/umbrella corporation.gif"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(631, 631));
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 320, 56, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 350, 80, 16);
        getContentPane().add(txtUsuarioAdm);
        txtUsuarioAdm.setBounds(250, 320, 130, 26);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alta de administrador");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 230, 260, 40);

        btnGuardarAdmin.setText("Guardar");
        btnGuardarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarAdmin);
        btnGuardarAdmin.setBounds(240, 510, 150, 29);

        btnSalir2.setText("Salir");
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir2);
        btnSalir2.setBounds(390, 510, 170, 29);

        btnRegresarMenuPrinc.setText("Regresar al menu anterior");
        btnRegresarMenuPrinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuPrincActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresarMenuPrinc);
        btnRegresarMenuPrinc.setBounds(10, 510, 230, 29);
        getContentPane().add(txtpasword);
        txtpasword.setBounds(250, 350, 130, 26);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(230, 570, 190, 29);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/umbrella corporation.gif"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 500, 180);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/negro.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 630, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMenuPrincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuPrincActionPerformed
      AdministradorPrincipal adm=new AdministradorPrincipal();
    adm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnRegresarMenuPrincActionPerformed

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
      System.exit(WIDTH);
    }//GEN-LAST:event_btnSalir2ActionPerformed

    private void btnGuardarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAdminActionPerformed
//        Crear();


//         ArchivoEscrituraAdministrador ApE =new ArchivoEscrituraAdministrador();
//         
//         
//         ApE.setNombre(txtUsuarioAdm.getText());
//         ApE.setPasword(txtpasword.getText());
////         ApE.setPasword(txtpasword.getPassword());
//         
//        try {
//             if(ApE.saveAdministradores()){ // Se llama la funcion guardar de alumno
//                   JOptionPane.showMessageDialog(this,"El usuario se guardo exitosamente");
//                   txtUsuarioAdm.setText("");
//                   txtpasword.setText("");
//                   
//             }
//            
//        } catch (Exception e) {
//            System.out.println("Error: "+e.getLocalizedMessage());
//        }
//        
//
//this.dispose();
List<ArchivoEscrituraAdministrador> listaAdministrador= new ArrayList<>();
         LecturaDeDatos fr=new LecturaDeDatos();
         listaAdministrador=fr.ObtenerAdministrador();
        
        if(fr.BuscarAdministrador(txtUsuarioAdm.getText())!=-1){
            JOptionPane.showMessageDialog(this,"No se pudo agregar al Administrador ya esta existente" );
        }
        else{
        
        
            ArchivoEscrituraAdministrador AdministradorTemp=new ArchivoEscrituraAdministrador();
            AdministradorTemp.setNombre(txtUsuarioAdm.getText());
            AdministradorTemp.setPassword(txtpasword.getText());
          
            AdministradorTemp.GuardarAdministrador2();
            JOptionPane.showMessageDialog(this,"El Administrador fue registrado exitosamente");
            
            int id=listaAdministrador.size()+1;

        }
        txtUsuarioAdm.setText("");
        txtpasword.setText("");
       
        



    }//GEN-LAST:event_btnGuardarAdminActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

 
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardarAdmin;
    private javax.swing.JButton btnRegresarMenuPrinc;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtUsuarioAdm;
    private javax.swing.JPasswordField txtpasword;
    // End of variables declaration//GEN-END:variables
}
